[package]
edition = "2021"
name = "recommenders"
version = "0.1.0"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
csv = "1.1"
nalgebra = "0.29"
rand = "0.8"
rand_distr = "0.4.2"
